### ISSUE TITLE
Hue Motion - Motion Status & Active

### ISSUE THREAD

**Issue by pkg246** [Foddy/node-red-contrib-huemagic#172]
**Describe the bug**
I cant get any status from the Motion Event. In the Function Block I have the following

msg.payload.motion
return msg;

Also with the the Active Event, When its Active it outputs "null" and when inactive it outputs "false". Is this correct or should it have "True" when its Active?

**Expected behavior**
Expected to get a "True" or "False" Status from the Motion Event and Clarification on the Active Event as above

**Please complete the following information:**
 - NodeRED version: [v1.0.6]
 - NodeJS version: [..12.16.2.]
 - Device running NodeRED: [.Raspberry Pi 4..]

**Comment by Foddy** [comment]
This is fixed with the latest release (at least the invalid active state). Your function block seems incorrect. If you want to return the motion state, just return the motion state ;)

`return msg.payload.motion;`

This should output a boolean with the current motion state if something is moving in front of the sensor.
