### ISSUE TITLE
Document virtual pressing of the Hue Bridge link button

### ISSUE THREAD

**Issue by jontywigster** [Foddy/node-red-contrib-huemagic#186]
**Is your feature request related to a problem? Please describe.**
A feature listed in [https://flows.nodered.org/node/node-red-contrib-huemagic](https://flows.nodered.org/node/node-red-contrib-huemagic) is 'Supports virtual pressing of the button on the Hue Bridge (Link Button)'. Could how this is actually achieved in Node Red be documented?

**Describe the solution you'd like**
[https://flows.nodered.org/node/node-red-contrib-huemagic](https://flows.nodered.org/node/node-red-contrib-huemagic) to be updated, whether directly or by changing whatever generates this page, with instructions of how the virtual button press can be achieved.

**Describe alternatives you've considered**
Finding, then climbing a ladder to press the Link Button on each of my Hue Bridges; Replacing Hue with something that doesn't need a physical button press when I change my phone.

**Additional context**

**Comment by Deggle** [comment]
I don't want to give you guys a hard time because all your work on this is absolutely imagine - but could someone _please_ comment on here with the actual solution? It's great that you've accepted the request to add it into the documentation, but it would be really good to actually know the solution while we wait for that!? It's listed as a feature so there is surely a quick one-liner someone could past in here!?!? Many thanks, Tim

**Comment by Foddy** [comment]
I am sorry for this late response. This feature has been more or less removed from the current API by the Philips Hue bridge and is no longer available in this form.

So we have to press the button physically I guess in future.
