### ISSUE TITLE
Extended Mode

### ISSUE THREAD

**Issue by lespatots** [Foddy/node-red-contrib-huemagic#20]
I found some problems trying to use the extended mode function. Simple mode is fine.

1) Setting ‘on’ to false has no effect the only action seems to be on (extended mode)
2) It would be good to add in some more range checking. Brightness values greater than 100 produce a library error?
   "Error: Philips Hue: 7, invalid value, 508,, for parameter, bri”

3) Brightness 0 isn’t off (I think that’s a Hue bridge limitation) but IMHO I think zero should be off also if you use 0 to 100 rather than 0 to 254 then the possible range of brightness levels is reduced?

4) ct is fine using megakelvin !!! but weird IMHO but what about saturation etc?

5) I wonder whether the excellent info might be improved a bit to explain whether commands are additive. So if I send ‘on' without colour and follow up with a colour setting without ‘on’ what is the result?

6) Would it be better to match the parameter names to the Philips ones (even if they are cryptic)?

**Comment by Foddy** [comment]
Hi lespatots!
Thank you for this nice feedback and sorry for my late response!

Setting "on" to "false" should work as expected now with v1.3.1. I also added a brightness setting validation _(can't understand why I didn't before…)_ and lights / groups are now turning off if the setting is "0". You were right, for some reasons Philips' API is not turning off the lights if the brightness setting is 0.

The saturation setting is something that I totally missed from the API docs – but now obviously added with the update ;)!

With the improved input "algorithm" in v1.3.1 all nodes are now working "additive". You also don't have to pass in the "msg.payload.on" parameter anymore and all future commands are simply updating the light / group / sensors. I added this info in the features section in the README file with a simple sentence. You're totally free to contribute if you have some improvements for the README of even the actual code :)!

I decided to use own customized parameters for HueMagic because of three reasons:

1. You also mentioned it. They are cryptic in some cases and not easy to remember (often).
2. If they were all identical then users would probably think, that they also work the same. With Philips Hue API for example you have to pass in a value between 0 and 254 to set the brightness level of a light bulb. In HueMagic this setting is a more convenient "percent" parameter which makes things easier for users – I guess (I hope).
3. With customized parameter names HueMagic is able to keep it's nodes and API "alive" with internal recalculations and without having the user to manually update all the nodes, just because Philips changed / removed / unnamed some parameters in their API.

I am closing this issue for now. Feel free to answer back if you don't agree with my last arguments 👍 !
