### ISSUE TITLE
Long delay between pressing button on dimmer switch and node responding

### ISSUE THREAD

**Issue by Roaders** [Foddy/node-red-contrib-huemagic#201]
**Describe the bug**
Sometimes it can take up to 5 seconds for hue magic to emit a message after pressing a button on my dimmer switch.

**Please complete the following information:**
 - Node-RED version: [1.0.6]
 - NodeJS version: [12.16.3]
 - Device running Node-RED: [raspberry pi 3]

If I understand it correctly the button press detection is done by polling the hue bridge. Can I decrease the poll time and will this increase the responsiveness? Is there no way of adding a callback url to the bridge to directly inform us when a button has been pressed?

**Comment by dongennl** [comment]
Hi, yes the polling interval is set on the Hue bridge main node. Think the default is 3 seconds.
Keep in mind that lowering this might cause a lot of additional traffic to the Hub. (Think it might ping the Hub for each Light/Switch node in your project); 
I had to increase the polling time due to rate limiting on the Hub.

**Comment by Foddy** [comment]
Hi Roaders,

as @dongennl mentioned before, you can try lowering the poll interval in your bridge settings to get faster reaction times but it could cause some rate limiting errors. Since Philips Hue unfortunately does not provide any other API model (websockets / webhooks ...), 100% real-time queries cannot be realized at the moment.

**Comment by Roaders** [comment]
What sort of polling interval would you recommend? I think I have it less than a second at the moment.
Thanks
