### ISSUE TITLE
multiple press on hue Tap

### ISSUE THREAD

**Issue by elnanini** [Foddy/node-red-contrib-huemagic#23]
Hi, great project!
Would it be possible to detect a second press of the same button of a tap? Wen I press button 1, the tap node sends the corresponding json object, if I press it again nothing happens until I press a different button.
Thanks!

**Comment by Foddy** [comment]
Hi @elnanini,

unfortunately this is currently not available due to Philips Hue's API for Hue Tap devices. Since there is no real time communication possible between the Hue Bridge and HueMagic, HueMagic polls every couple seconds the current status of the device and compares it with the old one. 

Unlike other devices like the light bulbs or the Hue Dimmer Switch, Hue Tap is the only one which doesn't send state attributes like a _lastupdated_ timestamp or so. So for now HueMagic is unable to check if the Button pressed only once or multiple times...

For now (until Philips Hue updates their API) the only solution to make this logic happen is using a Hue Dimmer Switch or an Amazon Dash button... :S
