### ISSUE TITLE
Hue Groups, allOn and anyOn.

### ISSUE THREAD

**Issue by dionmes** [Foddy/node-red-contrib-huemagic#26]
In Hue groups there is an issue with allOn and anyOne, which does not allow to separate groups. They are always set to true which influence all the lights instead of only the Hue group.

Hmmm.. after some further testing it looks like 1 group (living room) is tying all the lights together ?!?! I have recreated the group, but same results...

**Comment by Foddy** [comment]
Hey @dionmes,

I don't know if I understood your problem correctly. What exactly do you want to achieve with the information from the allOn / anyOne attributes? Do you mean with "tying all lights together" that commands to your living room group are also sent to lights that are not included in this group?

**Comment by dionmes** [comment]
My issue is that if I send 'on:true' to the Living group, the sleeping and office group also go on and off (these are all the groups in use with Hue). I think it has to do with allOn and anyOne, but I am not sure.

**Comment by Foddy** [comment]
Hmm okay… That is very odd…

The allOn and anyOne parameters are just "read only" and shouldn't affect any other groups on your Hue. Something must have gone wrong with the configuration of your group via third-party apps. What happens if you turn all the lights on on a specific group with an external app (like the official Philips Hue app)? Does that work as expected?

For me, it seems like a specific light in a group has been assigned to several groups.

**Comment by dionmes** [comment]
Yes, well I have the same group in the Philips app and in homekit (they get synchronised) and in the app and homekit they work as expected (separate controls). It is only when I address them via node-red and the huemagic group node (great work by the way) that it controls the other lights as well. Don't spend to much time on this if it is not easily discovered. I now address them as two separate lights and that works fine.

**Comment by dionmes** [comment]
Ok, I updated Huemagic and tried it our with the 'living room' group again and now its working fine ...?!?! Must be some bit fallen over. Thx for the support.

**Comment by Foddy** [comment]
Glad to read that! ;)
