### ISSUE TITLE
Searching lights...

### ISSUE THREAD

**Issue by shining01** [Foddy/node-red-contrib-huemagic#27]
Hello,

i have a Problem finding any of my lights. I have configured my bridge. API Key all is well. But the software doens't find any lights. Why? Thanks

**Comment by Foddy** [comment]
Hi @shining01,

I wasn't able to reproduce this error. Can you please tell me the device on which NodeRED is running? Is this device connected to your router via Wifi or LAN?

**Comment by Foddy** [comment]
Please reopen this issue if you still face this error.

**Comment by MatzeMuc86** [comment]
The idea is to have an external app (the Philips hue app) for choosing the specific color/brightness once. As soon as this is done I would like to recall the specific color/brightness via node red e.g. via a switch in the dashboard. Scenes would be an alternative but i would like to control single lights instead of scenarios that effect all lights of a room. Any suggestion? Maybe the solution is even more trivial and I am thinking to complicate.

**Comment by MatzeMuc86** [comment]
Sorry, wrong thread!
