### ISSUE TITLE
Groups no longer report brightness

### ISSUE THREAD

**Issue by hurenkam** [Foddy/node-red-contrib-huemagic#277]
While making the switch to the new node red 2.1.4 and hue magic 4.0.4 versions, which have the refactored API, i noticed that group status messages no longer report brightness or brightness changes. Only on: true/false is reported in the payload. Previously a brightness used to be reported as well, and some of my flows use that (but it is not a major input for my logic though, so I can also manage without it).
Was this an intentional change? Or is it a bug?

**Comment by Foddy** [comment]
Unfortunately it's not possible with the newest API from Philips to get the current brightness from a Group / Zone.

The old API had this feature, now they removed it because groups / zones can contain different kind of devices besides lights. Not every device inside a group for example has the capabilities to set a brightness, different colors...

If they would, I also don't see what kind of values the bridge should output for the group if one light is set to 100% brightness and yellow, when another is set to 50% blue.

Should it be 75% brightness and green then? :S

I would suggest you to put a light node right after the group node where you know that it is linked with the group and get the brightness value from this light for the whole group, if you still need to access this value. It luckily happens all in real time without any significant overhead (usually) to your bridge when using multiple, additional nodes with the v4, so maybe this is a solution for you (and others relying to this previous feature).

**Comment by hurenkam** [comment]
Ah, yeah if bridge API no longer offers this, then i guess I have to find another way to keep track.
Thanks.
