### ISSUE TITLE
Wrong values when changing color via RGB

### ISSUE THREAD

**Issue by MatzeMuc86** [Foddy/node-red-contrib-huemagic#30]
When trying to change the color of hue lights by sending RGB to the hue light, the resulted output of the hue light varies in the RGB values. See attached Node-Red Flow as well as the debug output.
Anything wrong in my flow or is there a bug in huemagic?

![debug](https://user-images.githubusercontent.com/35663719/35196652-47951af0-fed5-11e7-9d2e-121b1311e951.JPG)

Node-Red Flow:
`[{"id":"107d276c.8ccc29","type":"debug","z":"51b5b710.9656e8","name":"Empfangen","active":true,"console":"false","complete":"payload","x":1510,"y":820,"wires":[]},{"id":"4b6eb2db.69714c","type":"hue-light","z":"51b5b710.9656e8","name":"Couch (Hue Go)","bridge":"e7b6a026.08bf4","lightid":"3","x":1320,"y":820,"wires":[["107d276c.8ccc29"]]},{"id":"2381830e.45626c","type":"function","z":"51b5b710.9656e8","name":"HueCouchChillen","func":"msg.payload={\n\t\"on\":true,\n\t\"brightness\":57,\n\t\"rgb\":[255,187,92]\n};\nreturn msg;","outputs":1,"noerr":0,"x":1090,"y":820,"wires":[["4b6eb2db.69714c","d0d667e1.4f00b8"]]},{"id":"ffb7044.9e6bff8","type":"link in","z":"51b5b710.9656e8","name":"hue-chouch-chillen","links":["413932d5.eac6cc","c6202c30.62ead","619b769d.3f5938"],"x":695,"y":780,"wires":[["2381830e.45626c"]]},{"id":"d0d667e1.4f00b8","type":"debug","z":"51b5b710.9656e8","name":"Senden","active":true,"console":"false","complete":"payload","x":1320,"y":760,"wires":[]},{"id":"e7b6a026.08bf4","type":"hue-bridge","z":"","name":"Philips hue neu","bridge":"192.168.186.40","key":"xxx","interval":"3000"}]`

**Comment by Foddy** [comment]
Hi @MatzeMuc86,

there is nothing wrong with your flow regarding this "issue".

Since Philips Hue lamps, unlike regular monitors use the "xy" colorspace by default, there must be a conversion from HEX/RGB to xy by HueMagic. HueMagic therefore uses an optimized [algorithm](https://github.com/PhilipsHue/PhilipsHueSDK-iOS-OSX/commit/f41091cf671e13fe8c32fcced12604cd31cceaf3#diff-9cde285b4d323fc56b2ba508430e5f5a) that slightly modifies your color code (HEX/RGB) to mimic the color on your screen as much as possible on your lamps. Conversely, this means that you, as you have already noticed, get back a slightly different color value from the lamps as a result.

If you want to perform actions that should react to the color of a lamp, I advise you to define color ranges and check if the return value is in one of your ranges.

I hope that has answered your question.

**Comment by MatzeMuc86** [comment]
Thank you for your quick reply.
Do you have a hint how to properly control the hue light if I want to tell the specific color that is set externally? Doing so via reading RGB values and sending them is obviously not the right way but doing so via RGB is not important for me. Any other way of reading and writing the precise values?
Thank you and best

**Comment by Foddy** [comment]
So you have a lamp in which the color was set via an external program, if I understood you correctly. The only thing I don't understand is how you want to use the color value that you get from HueMagic?

Do you try to replicate a color to another lamp?
