### ISSUE TITLE
Cannot Action groups and lights 

### ISSUE THREAD

**Issue by Flup23** [Foddy/node-red-contrib-huemagic#31]
Hello,

i just downloaded 1.3.4 and i have the same "**SyntaxError: Unexpected token =**" Problem like vBiggles.

I only can action scenes, but no lights and groups.
I updated NPM to Version 5.6.0, but doesn't help.
Can you or vBiggles please help me with the Problem and describe your solution? I'm not so firm with Linux, NPM and the details of Node-Red

thx

**Comment by frewie** [comment]
I have exactly the same problem. Any ideas?

**Comment by pcvdt** [comment]
Same problem here. Also when I use the nodes for the lights I can't control them from the hue app anymore. When I remove the nodes from my flows everything works well. A solution would be great! I'm looking forward to using all the nodes!
TIA!

**Comment by erwandime** [comment]
The same problem for me...

**Comment by Foddy** [comment]
Can somebody share a sample flow?
I am trying to reproduce this error but for me everything is looking good?!

**Comment by erwandime** [comment]
Problem with NodeRed in docker....hue magic don't work and zwave / harmony, etc don't install !

On RPI, it works !

**Comment by Foddy** [comment]
So it seems that this bug is not HueMagic related? Is that correct?

**Comment by erwandime** [comment]
Correct !

**Comment by pcvdt** [comment]
I'm running node red on a RPI. I installed Raspbian with the NOOBS install (https://www.raspberrypi.org/downloads/noobs/). As far as I'm aware I never installed Docker...

**Comment by pcvdt** [comment]
When I deploy I get this message: "
17-2-2018 22:00:24node: Wandlamp Woonkamer
msg : error
"SyntaxError: Unexpected token =""

This is a sample flow:

[{"id":"bfbbd15b.15837","type":"hue-light","z":"18365d53.db6a5b","name":"Wandlamp Woonkamer","bridge":"ca4308fc.cc49d8","lightid":"7","x":350,"y":160,"wires":[["615ee498.af99dc"]]},{"id":"615ee498.af99dc","type":"debug","z":"18365d53.db6a5b","name":"","active":true,"console":"false","complete":"payload","x":580,"y":160,"wires":[]},{"id":"61198a7.c9fc8f4","type":"inject","z":"18365d53.db6a5b","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"x":130,"y":140,"wires":[["bfbbd15b.15837"]]},{"id":"b513d540.1d1348","type":"inject","z":"18365d53.db6a5b","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"x":130,"y":180,"wires":[["bfbbd15b.15837"]]},{"id":"ca4308fc.cc49d8","type":"hue-bridge","z":0,"name":"Philips hue","bridge":"192.168.1.72","key":"TJ18GnK13njK2w-iz8fqI7yf9cqwnHhV4NJIPyqf","interval":"3000"}]

**Comment by misakm** [comment]
Hi I got the same issue. Would you please help? Since updated to 1.41 cannot control any light. 
5 Mar 12:40:53 - [error] [hue-light:8353b695.130868] SyntaxError: Unexpected token =
I have tried to remove and install huemagic again but this did not help.

More info
Starting as a systemd service.
Started Node-RED graphical event wiring tool..
5 Mar 12:39:46 - [info]
Welcome to Node-RED
===================
5 Mar 12:39:46 - [info] Node-RED version: v0.17.5
5 Mar 12:39:46 - [info] Node.js  version: v4.4.5
5 Mar 12:39:46 - [info] Linux 4.1.7-v7+ arm LE
5 Mar 12:39:49 - [info] Loading palette nodes
5 Mar 12:39:57 - [info] node-red-contrib-pimatic@1.1.2 (/home/pi/.node-red/node_modules/node-red-contrib-pimatic/pimatic) started
5 Mar 12:39:59 - [info] Dashboard version 2.8.2 started at /ui
5 Mar 12:40:04 - [info] Settings file  : /home/pi/.node-red/settings.js
5 Mar 12:40:04 - [info] User directory : /home/pi/.node-red
5 Mar 12:40:04 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
5 Mar 12:40:04 - [info] Server now running at http://127.0.0.1:1880/
5 Mar 12:40:04 - [info] Starting flows
5 Mar 12:40:05 - [info] Started flows
5 Mar 12:40:53 - [info] Stopping flows
5 Mar 12:40:53 - [info] Stopped flows
5 Mar 12:40:53 - [info] Starting flows
5 Mar 12:40:53 - [error] [hue-light:8353b695.130868] SyntaxError: Unexpected token =
5 Mar 12:40:53 - [info] Started flows

**Comment by NsjrZ** [comment]
I have the same issue - both light and group have the same error message, "SyntaxError: Unexpected token =m ". I have also removed and re-installed hue magic but no change. Suggestions?

**Comment by Foddy** [comment]
For me, it looks like you're using an older version of Node.js.
Unfortunately HueMagic is only optimized and well tested for Node.js 8.x and 9.x.

Can you consider upgrading your node.js version to 8+?
