### ISSUE TITLE
Wrong hex and rgb information

### ISSUE THREAD

**Issue by EdikHa** [Foddy/node-red-contrib-huemagic#5]
Hi, 
I just made a small Node with a Hue Light and Hue Group and somehow the output rgb and hex code is wrong. 
For example: 
Hue Group/Light input is rgb(255,0,0) or hex code: #ff0000 the reading output is rgb(255,254,88).

**Comment by Foddy** [comment]
Hi,

yes this is correct. The reason is that directly after you update a node / light, the module tries to get the current light bulb color and you often get the color of the transition to your wished color. In your case it was a yellowish color at the time of the request.

There is also to mention, that converting the current exact color into hex / rgb is not possible, since every light bulb / model has its own light color "limits". The algorithm behind of it tries to convert your "red" into the closest possible color that your light bulb can display.

That means that you unfortunately will never get the exact hex / rgb code back from your light bulb that you initially pushed to the node until Philips makes these conversions for each light bulb specifications directly on their bridge and offers them in their API.
