### ISSUE TITLE
FR: Ability to enable and disable rules

### ISSUE THREAD

**Issue by oskretc** [Foddy/node-red-contrib-huemagic#82]
Feature Request:

Having the ability to enable and disable rules from Node-Red will be fantastic. think about disabling the turn on or off automatically based on PIR sensors depending on other factors, but still be able to use the PIR sensor for detecting presence. Thanks

**Comment by readeral** [comment]
Is there a reason you'd like to have your 'rule' logic remain in the hue app, instead of outsourcing all of your logic to node red? I don't have Hue sensors, so haven't experienced that side of the Hue ecosystem.

**Comment by oskretc** [comment]
Agree, most of my logic is in node red, there are just a few reasons to have this functionality.

- If you disable the Sensor, you lose the ability to "see", no detection, no temperature, no lux is updated. so this is not an option.
- Speed: the purpose of a light controlled by a presence detection sensor is to act upon it as fast as the detection. I've seen that the path: Sensor -> Hue Bridge -> HomeAssistant -> Node-Red -> HomeAssistant -> Hue Bridge -> Light is not always deterministic and there are delays that are not nice. So having the rules in the Hue Bridge is kind of a shortcut, but still having the ability to control when those rules are applied using Node Red.

**Comment by readeral** [comment]
Yeah ok, with HomeAssistant in the mix that is a long round trip. I personally don't use home assistant so don't know what the latency is like with it included, but because I use Xiaomi motion sensors, I'm forced to utilise NodeRed to bring those two platforms together.
In my experience I've not had any delay from the input of a motion sensor to triggering my hue lights.

That being said, given the rules are exposed by the Hue API ([see here if you have a free developer account](https://developers.meethue.com/develop/hue-api/6-rules-api/)), then there's no harm in trying to code it up and submitting a pull request.

**Comment by Foddy** [comment]
You can enable / disable rules from version 2.0+
