### ISSUE TITLE
How to get the state of a bulb for toggling?

### ISSUE THREAD

**Issue by Tscherno** [Foddy/node-red-contrib-huemagic#86]
Hi,

i want to use a (Homematic) button to switch a Hue bulb from Off to on and on to off. The problem is that i need to read the current state. If i get it right, there is only an Input+Output node. The problem here is, that this node can't be used only for reading the state, but also triggers if i change the state in the next step of the flow. Any suggestions how to implement a toggle?

That was the (endless looping) try:
[{"id":"3004675f.041798","type":"hue-light","z":"250dd799.5509c","name":"Schlafzimmer Matthias","bridge":"e37e7857.36805","lightid":"13","colornamer":true,"x":520,"y":180,"wires":[["d33490ee.88ec78"]]},{"id":"d33490ee.88ec78","type":"switch","z":"250dd799.5509c","name":"","property":"payload.on","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":690,"y":120,"wires":[["e8fa4719.552b38"],["4fed7f73.22a298"]]},{"id":"4fed7f73.22a298","type":"change","z":"250dd799.5509c","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":850,"y":140,"wires":[["512b4763.581798"]]},{"id":"e8fa4719.552b38","type":"change","z":"250dd799.5509c","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":850,"y":100,"wires":[["512b4763.581798"]]},{"id":"512b4763.581798","type":"hue-light","z":"250dd799.5509c","name":"Schlafzimmer Matthias","bridge":"e37e7857.36805","lightid":"13","colornamer":true,"x":1060,"y":120,"wires":[[]]},{"id":"3af55973.5a87ee","type":"change","z":"250dd799.5509c","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":470,"y":120,"wires":[["3004675f.041798"]]},{"id":"bc5d7add.67c44","type":"ccu-value","z":"250dd799.5509c","name":"","iface":"HmIP-RF","channel":"0001978858DAD8:2 Taster Schlafzimmer Matthias Oben","datapoint":"PRESS_LONG","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":true,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":200,"y":180,"wires":[["3af55973.5a87ee"]]},{"id":"3b04d708.362958","type":"inject","z":"250dd799.5509c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":100,"wires":[["3af55973.5a87ee"]]},{"id":"e37e7857.36805","type":"hue-bridge","z":"","name":"Philips hue","bridge":"192.168.1.116","key":"xiIi0TPXcEbJPLcHv4mqY-QXREMN2EmLYkZVPOcO","interval":"3000"},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":true,"cuxdEnabled":true,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":"memory"}]

**Comment by PiRune** [comment]
What I did to make a toggle, was to connect a time stamp inject node to the hue light node and then add a function node setting a flow variable based on the light status.

Then separately connect a button/gpio node to a function node with an if function inverting the current state (based on the flow variable) and then connecting that node to a hue light node (an identical, but separate, node to the one delivering the event). This works.

HOWEVER, 
I am also looking for a way to get current light status, since the automatic light events are too slow. I just migrated from custom python scripts (using phue) to node-red and hue magic. In python I had no separate flow for storing the state of the lights, but simply requested the state on demand when needed, which was much faster and more reliable. Please add a way to get light state on demand.

**Comment by PiRune** [comment]
Use flow variables as a workaround. This works great in my setup, but would be nice to se implementet to a simple toggle node:

[your node with payload "toggle"] -> [function node: if "toggle" received set variable1 to True] -> [your hue light node] -> [function node: set hue state as variable2] -> [if variable1 is True, then if variable2 is on then send payload "off", else send payload "on"] - > [your hue light node]

**Comment by PiRune** [comment]
Use flow variables as a workaround. This works great in my setup, but would be nice to se implementet to a simple toggle node:

[your node with payload "toggle"] -> [function node: if "toggle" received set variable1 to True] -> [your hue light node] -> [function node: set hue state as variable2] -> [if variable1 is True, then if variable2 is on then send payload "off", else send payload "on"] - > [your hue light node]

**Comment by Tscherno** [comment]
But that only works if I switch the lights via NodeRed, right? If i switch it via App/switch the state-variable wouldn't be correct anymore?

**Comment by PiRune** [comment]
No to your first question and yes to your second.

The flow variable only needs to be correct when you toggle via node-red. When you turn the light on or off via app, switch or other flow, the variable is not used for anything.

My suggested flow above will always act correctly because it checks the lamp state every time you send a toggle payload (that's what the first hue light node does). After checking the state, it will change it to the opposite.

**Comment by PiRune** [comment]
The flow variable only needs to be correct when you toggle via node-red. When you turn the light on or off via app, switch or other flow, the variable is not used for anything.

My suggested flow above will always act correctly because it checks the lamp state every time you send a toggle payload (that's what the first hue light node does). After checking the state, it will change it to the opposite.

**Comment by PiRune** [comment]
The flow I suggested will change the light state to the opposite, regardless of how the current state was set (i.e it makes no difference if you also use a light switch or app).

This is because the light state flow variable is updated whenever the flow is activated (which is also the only time the variable is needed).

Se a quick and dirty version below.
![screenshotflow](https://user-images.githubusercontent.com/20454469/62701267-22db7300-b9e4-11e9-9f4e-61aae5c38999.png)

By design the top function does not change the state of the lamp, but only sets the toggle flow variable to "on" and activates the first hue node by simply forwarding the toggle payload, which is not understood by the hue node. After receiving the payload the hue node sends its own payload containing the on/off state. This payload is received by the next function node, which sets the state as the light state flow variable and then activates the last function node by forwarding the payload. The last function node then checks whether the toggle flow variable is "on" (flag raised). If this is true, it reads the light state flow variable (on/off) and then sends the opposite command as a payload to the last hue node, which then carries out the task of changing the actual light state.

(the reason the displayed state of the two identical hue light nodes are not in sync in the screen shot, is that these nodes only update the state every few seconds, UNLESS activated. The bottom hue node was activated last and the top hue node was not yet updated when the screen shot was taken. This delay makes no difference to the flow however, because the node is activated when needed).

**Comment by Foddy** [comment]
Check out the new toggle function in 2.0+
