### ISSUE TITLE
motion sensor keeps loosing connection

### ISSUE THREAD

**Issue by Eggn1n3** [Foddy/node-red-contrib-huemagic#9]
Seems that after a few hours the motion sensor (including subsensors like lightlevel) loses connection. Node red shows "disconnected" for these nodes. When I redeploy node red they get connected again. Would it be possible to have some reconnect mechanism implemented?

**Comment by Foddy** [comment]
Hi,

This shouldn’t be the case normally. HueMagic is not able to establish a persistent (socket) connection due to Philipe Hue’s api architecture, so it retries to get event changes after a preconfigured time interval in your Hue Bridge node.

Can you please tell me some more information about your environment? Are you using a static IP for your Hue bridge? Are you trying to connect to a bridge locally or over the internet? What is your NodeRED and Node.JS version? Did this happened just one time or more often?

**Comment by Eggn1n3** [comment]
Hi Foddy,
I am using a static IP address on my HUE bridge (v1). Node-red connects to the bridge locally.
Node-red version: v0.17.5
NodeJS: v6.11.3
Platform: Raspberry PI 3
The disconnects happen all the time, even the HUE lights show disconnect so now and then.

I do have another Rasperry Pi with node-red v0.16.2 which I can try as well to see if it makes a difference. Is there any log file I can provide you that would help?

Thanks.

**Comment by lucwuyts** [comment]
Hi Eggn1n3,  i have seen this only a few times, but this was when the connection with the bridge was hindered too much by walls and other things.

**Comment by Foddy** [comment]
Unfortunately I could not reproduce this error on the same environment. Have you tried it on another environment @Eggn1n3?
